version: 0.2

env:
  parameter-store:
    S3_BUCKET: "/portfolio/static-site/s3-bucket"
    CLOUDFRONT_DISTRIBUTION_ID: "/portfolio/static-site/cf-distribution-id"
    
phases:
  install:
    commands:
      - echo "Install phase - nothing to install for basic static site"
  build:
    commands:
      - echo "Build phase - add npm/yarn build commands here if you move to a JS framework"
  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync . s3://$S3_BUCKET --delete --exclude ".git/*" --exclude "buildspec.yml"
      - echo "Creating CloudFront invalidation..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
